version: "3.3"

services:
  backend:
    build: .
    ports:
      - "8030:8030"
    depends_on:
      - mongodb

  mongodb:
    image: mongo
    ports:
      - "27019:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=user
      - MONGO_INITDB_ROOT_PASSWORD=password
    volumes:
      - mongodb_data:/data/db

volumes:
  mongodb_data:
